name: Check dependencies

on:
  schedule:
    - cron: "45 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: mkdir -p app/src/debug && echo $FIREBASE_CONFIG > app/src/debug/google-services.json
    - name: Check dependencies
      run: ./gradlew dependencyUpdates
